2024-09-21 23:30:18,229 | INFO | "test_challenge" выполнен успешно
2024-09-21 23:30:18,230 | WARNING | Неверный тип данных для объекта Runner
Имя может быть только строкой, передано int
2024-09-21 23:30:18,231 | WARNING | Traceback (most recent call last):
  File "D:\ProjectKarsar\tests_12_4.py", line 88, in test_run
    rn = Runner(2)
         ^^^^^^^^^
  File "D:\ProjectKarsar\tests_12_4.py", line 20, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int

2024-09-21 23:30:18,231 | WARNING | Неверная скорость для Runner
Скорость не может быть отрицательной, сейчас -5
2024-09-21 23:30:18,233 | WARNING | Traceback (most recent call last):
  File "D:\ProjectKarsar\tests_12_4.py", line 77, in test_walk
    wal = Runner("Вася", -5)
          ^^^^^^^^^^^^^^^^^^
  File "D:\ProjectKarsar\tests_12_4.py", line 25, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5

